apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
spec:
  volumes:
    - name: hello-storage
      persistentVolumeClaim:
        claimName: hello-pvc
  containers:
  - name: hello-spec
    image: alpine:latest
    stdin: true             # Keep stdin open on the container(s) in the pod, even if nothing is attached.
    tty: true               # Allocated a TTY for each container in the pod.
    volumeMounts:
    - name: hello-storage
      mountPath: /data/hello/container
    env:
    - name: DEMO
      value: "Test it"
    - name: SERVER_URI
      valueFrom:
        configMapKeyRef:
          name: special-config       # name of the config map
          key: serverUri             # key of the config map property