apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-d-f
  labels:
    app: cats-f
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-f
  template:
    metadata:
      labels:
        app: cats-f
    spec:
      containers:
      - name: frontend
        image: jmnnr/soa-k8s-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 0.1
            memory: "400Mi"
