apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-d-b-db
  labels:
    app: cats-b-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-b-db
  template:
    metadata:
      labels:
        app: cats-b-db
    spec:
      containers:
      - name: backend
        image: jmnnr/soa-k8s-backend-db:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9999
        resources:
          limits:
            cpu: 0.1
            memory: "400Mi"
